using Pexita.Data.Entities.ShoppingCart;

namespace Pexita.Data.Entities.Payment
{
    public class PaymentModel
    {
        public int ID { get; set; }
        public string? PaymentOrderID { get; set; } // ! Generated by me
        public string? PaymentLink { get; set; } // ! Given by IDPay to redirect the user to payment page
        public long Amount { get; set; } // ! Total money paid by user
        public string? IDPayTrackID { get; set; } // ! Generated by IDPay to track transaction status
        public string? TransactionID { get; set; } // !Generated by IDPay. ID of the transaction being Done by user
        public string? CardNo { get; set; } // ! Credit Card number of the user
        public string? HashedCardNo { get; set; } // ! Hashed Credit card number
        public DateTime DateIssued { get; set; } // ! Datetime the payment was requested
        public DateTime? DateTimePaid { get; set; } // ! Generated by ID pay, Datetime (Timestamp) the purchase was done
        public bool? Successful { get; set; } // indicator whether the payment was successful or not
        public DateTime PaymentVerificationDate { get; set; } // Date when the purchase was verified
        public int? ShoppingCartID { get; set; } // !
        public ShoppingCartModel? ShoppingCart { get; set; } // !
    }
    public class PaymentSettings
    {
        public required string APIKey { get; set; }
        public required string CallbackAddress { get; set; }
        public bool isTest { get; set; }
    }

    public class PaymentDTO
    {
        public int ID { get; set; }
        public string? PaymentOrderID { get; set; }
        public string? PaymentLink { get; set; }
        public long Amount { get; set; }
        public string? IDPayTrackID { get; set; }
        public string? TransactionID { get; set; }
        public string? CardNo { get; set; }
        public string? HashedCardNo { get; set; }
        public DateTime DateIssued { get; set; }
        public DateTime? DateTimePaid { get; set; }
        public bool? Successful { get; set; }
        public DateTime PaymentVerificationDate { get; set; }
        public int? ShoppingCartID { get; set; }
        public required ShoppingCartDTO ShoppingCart { get; set; }
    }
}
